Cgi\SupplierBundle\Entity\Supplier:
    repositoryClass: Pim\Bundle\CustomEntityBundle\Entity\Repository\CustomEntityRepository
    type: entity
    table: supplier
    changeTrackingPolicy: DEFERRED_EXPLICIT
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            unique: true
        sortOrder:
            type: integer
        name:
            type: string
            length: 255
    manyToMany:
        users:
            targetEntity: Pim\Bundle\UserBundle\Entity\UserInterface
            joinTable:
                name: supplier_user
                joinColumns:
                  supplier_id:
                    referencedColumnName: id
                inverseJoinColumns:
                  user_id:
                    referencedColumnName: id
            cascade:
                - detach