services:
    supplier.job.job_parameters.default_values_provider.simple_csv_import:
        class: '%pim_connector.job.job_parameters.default_values_provider.simple_csv_import.class%'
        arguments:
            -
                - "%supplier.job.csv.import.name%"
        tags:
            - { name: akeneo_batch.job.job_parameters.default_values_provider }